name: Lint
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  awesome-lint:
    name: Awesome Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx awesome-lint
  typos:
    name: Typos checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
        with:
          files: ./README.md
  pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(Add|Update|Remove) .+"
          helpMessage: "Example: 'Add MO2'"
