name: Lint
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  awesome-lint:
    name: Awesome Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: npx awesome-lint@1.2.0
  typos:
    name: Typos checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@master
        with:
          files: ./README.md
