name: Check PR title
on:
  pull_request:
    types: [opened, edited, synchronize]
    paths: [README.md]

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(Add|Update|Remove) .+"
          helpMessage: "Example: 'Add MO2'"
